/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterpolatorIndexRouteImport } from './routes/interpolator.index'
import { Route as InterpolatorStocksRouteImport } from './routes/interpolator.stocks'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthSchwabCallbackRouteImport } from './routes/auth.schwab.callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksPushoverAlertsRouteImport } from './routes/api/public/hooks/pushover-alerts'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterpolatorIndexRoute = InterpolatorIndexRouteImport.update({
  id: '/interpolator/',
  path: '/interpolator/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterpolatorStocksRoute = InterpolatorStocksRouteImport.update({
  id: '/interpolator/stocks',
  path: '/interpolator/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSchwabCallbackRoute = AuthSchwabCallbackRouteImport.update({
  id: '/schwab/callback',
  path: '/schwab/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPushoverAlertsRoute =
  ApiPublicHooksPushoverAlertsRouteImport.update({
    id: '/api/public/hooks/pushover-alerts',
    path: '/api/public/hooks/pushover-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/interpolator/stocks': typeof InterpolatorStocksRoute
  '/interpolator/': typeof InterpolatorIndexRoute
  '/auth/schwab/callback': typeof AuthSchwabCallbackRoute
  '/api/public/hooks/pushover-alerts': typeof ApiPublicHooksPushoverAlertsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/interpolator/stocks': typeof InterpolatorStocksRoute
  '/interpolator': typeof InterpolatorIndexRoute
  '/auth/schwab/callback': typeof AuthSchwabCallbackRoute
  '/api/public/hooks/pushover-alerts': typeof ApiPublicHooksPushoverAlertsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/pricing': typeof PricingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/interpolator/stocks': typeof InterpolatorStocksRoute
  '/interpolator/': typeof InterpolatorIndexRoute
  '/auth/schwab/callback': typeof AuthSchwabCallbackRoute
  '/api/public/hooks/pushover-alerts': typeof ApiPublicHooksPushoverAlertsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/checkout/return'
    | '/interpolator/stocks'
    | '/interpolator/'
    | '/auth/schwab/callback'
    | '/api/public/hooks/pushover-alerts'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/checkout/return'
    | '/interpolator/stocks'
    | '/interpolator'
    | '/auth/schwab/callback'
    | '/api/public/hooks/pushover-alerts'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/pricing'
    | '/checkout/return'
    | '/interpolator/stocks'
    | '/interpolator/'
    | '/auth/schwab/callback'
    | '/api/public/hooks/pushover-alerts'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  PricingRoute: typeof PricingRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  InterpolatorStocksRoute: typeof InterpolatorStocksRoute
  InterpolatorIndexRoute: typeof InterpolatorIndexRoute
  ApiPublicHooksPushoverAlertsRoute: typeof ApiPublicHooksPushoverAlertsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interpolator/': {
      id: '/interpolator/'
      path: '/interpolator'
      fullPath: '/interpolator/'
      preLoaderRoute: typeof InterpolatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interpolator/stocks': {
      id: '/interpolator/stocks'
      path: '/interpolator/stocks'
      fullPath: '/interpolator/stocks'
      preLoaderRoute: typeof InterpolatorStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/schwab/callback': {
      id: '/auth/schwab/callback'
      path: '/schwab/callback'
      fullPath: '/auth/schwab/callback'
      preLoaderRoute: typeof AuthSchwabCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pushover-alerts': {
      id: '/api/public/hooks/pushover-alerts'
      path: '/api/public/hooks/pushover-alerts'
      fullPath: '/api/public/hooks/pushover-alerts'
      preLoaderRoute: typeof ApiPublicHooksPushoverAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSchwabCallbackRoute: typeof AuthSchwabCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSchwabCallbackRoute: AuthSchwabCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  PricingRoute: PricingRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  InterpolatorStocksRoute: InterpolatorStocksRoute,
  InterpolatorIndexRoute: InterpolatorIndexRoute,
  ApiPublicHooksPushoverAlertsRoute: ApiPublicHooksPushoverAlertsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
