/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSchwabCallbackRouteImport } from './routes/auth.schwab.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSchwabCallbackRoute = AuthSchwabCallbackRouteImport.update({
  id: '/auth/schwab/callback',
  path: '/auth/schwab/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/schwab/callback': typeof AuthSchwabCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/schwab/callback': typeof AuthSchwabCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/schwab/callback': typeof AuthSchwabCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/schwab/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/schwab/callback'
  id: '__root__' | '/' | '/auth/schwab/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSchwabCallbackRoute: typeof AuthSchwabCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/schwab/callback': {
      id: '/auth/schwab/callback'
      path: '/auth/schwab/callback'
      fullPath: '/auth/schwab/callback'
      preLoaderRoute: typeof AuthSchwabCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSchwabCallbackRoute: AuthSchwabCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
